name: global_renov_api
description: A server app using the shelf package, firebase and Docker.
version: 1.0.0
repository: https://github.com/242darkman/global-renov-dart-flutter

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.0
  firebase_dart: ^1.1.3
  firebase_verify_token_dart: ^0.0.7
  jwt_decoder: ^2.0.1
  logging: ^1.2.0
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_hotreload: ^1.5.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
